[global]
error_log = /dev/stderr
log_limit = 32768

emergency_restart_threshold = 10
emergency_restart_interval = 1m

process_control_timeout = 10s

[www]
user = root
group = root

listen = /var/run/php/php-fpm.sock
listen.owner = root
listen.group = root
listen.mode = 0666

pm = static
pm.max_children = 10
pm.max_requests = 10000

decorate_workers_output = no
catch_workers_output = yes
clear_env = no
